EDIT_H.PGM: edit_h.pgm.rpgle
ICONV_H.PGM: iconv_h.pgm.rpgle
ICONVFF_H.PGM: iconvff_h.pgm.rpgle
ERRNO_H.PGM: errno_h.pgm.rpgle
LBCPYNV_H.PGM: lbcpynv_h.pgm.rpgle
IOCTL_H.PGM: ioctl_h.pgm.rpgle
GSKSSL_H.PGM: gskssl_h.pgm.rpgle
LUWRKA_H.PGM: luwrka_h.pgm.rpgle
IFSIO_H.PGM: ifsio_h.pgm.rpgle
LDAP_H.PGM: ldap_h.pgm.rpgle
ILEDATE_H.PGM: iledate_h.pgm.rpgle
QANESERV_H.PGM: qaneserv_h.pgm.rpgle
PARMLIST_H.PGM: parmlist_h.pgm.rpgle
POLL_H.PGM: poll_h.pgm.rpgle
QLG_H.PGM: qlg_h.pgm.rpgle
QMHLJOBL_H.PGM: qmhljobl_h.pgm.rpgle
QP2USER_H.PGM: qp2user_h.pgm.rpgle
QSRLSAVF_H.PGM: qsrlsavf_h.pgm.rpgle
QTVAPI_H.PGM: qtvapi_h.pgm.rpgle
QP0LSTDI_H.PGM: qp0lstdi_h.pgm.rpgle
QSYSETID_H.PGM: qsysetid_h.pgm.rpgle
RESOLV_H.PGM: resolv_h.pgm.rpgle
RECIO_H.PGM: recio_h.pgm.rpgle
REXEC_H.PGM: rexec_h.pgm.rpgle
REGEX_H.PGM: regex_h.pgm.rpgle
SCANX_H.PGM: scanx_h.pgm.rpgle
SENDMAIL_H.PGM: sendmail_h.pgm.rpgle
QSNAPI_H.PGM: qsnapi_h.pgm.rpgle
SHM_H.PGM: shm_h.pgm.rpgle
SIGNAL_H.PGM: signal_h.pgm.rpgle
SPAWN_H.PGM: spawn_h.pgm.rpgle
STATVFS_H.PGM: statvfs_h.pgm.rpgle
SSL_H.PGM: ssl_h.pgm.rpgle
STDIO_H.PGM: stdio_h.pgm.rpgle
SOCKET_H.PGM: socket_h.pgm.rpgle
USRSPC_H.PGM: usrspc_h.pgm.rpgle
SQLCLI_H.PGM: sqlcli_h.pgm.rpgle