CLBNDPGM.PGM: CLBNDPGM-Simple_Bound_CL_Program.PGM.CLLE
CLBNDPGM.PGM: private TGTRLS = V7R4M0
CLBNDPGM.PGM: private ALWRTVSRC = *NO
CLBNDPGM.PGM: private OPTIMIZE = *FULL

CLMODULE.MODULE: CLMODULE.CLLE
CLMODULE.MODULE: private TGTRLS = V7R4M0
CLMODULE.MODULE: private ALWRTVSRC = *NO
CLMODULE.MODULE: private OPTIMIZE = *FULL

CLILEPGM.PGM: CLMODULE.MODULE
CLILEPGM.PGM: private TGTRLS = V7R4M0
CLILEPGM.PGM: private ALWRTVSRC = *NO
CLILEPGM.PGM: private OPTIMIZE = *FULL
CLILEPGM.PGM: private ACTGRP = NICKLITTEN
CHOOSEIASP.PGM: CHOOSEIASP-DOU_Question_and_Answer_CL_Example.pgm.clle