FREERPG.PGM: FREERPG-Nicks_Version.pgm.rpgle
FREERPG1.PGM: FREERPG1-RPGLE_Free.pgm.rpgle
FREERPG2.PGM: FREERPG2-ARCAD_Converter.pgm.rpgle
FREERPG3.PGM: FREERPG3-Cozzi_Converter.pgm.rpgle
IFSIMPROVE.PGM: IFSIMPROVE-IFS_Sample_Modernised_and_Improved.pgm.rpgle
IFSMODERN.PGM: IFSMODERN-IFS_Sample_modernised_RPG_Free.pgm.rpgle
IFSLEGACY.PGM: IFSLEGACY-IFS_Sample_legacy_RPG_Column_Based.pgm.rpgle
OLDRPG.PGM: OLDRPG-old_rpg400_code.pgm.rpgle
OLDTAGRPG1.PGM: OLDTAGRPG1-old_rpg400_with_goto_tag_subroutine.pgm.rpgle
OLDTAGRPG2.PGM: OLDTAGRPG2-old_rpg400_lightly_neater.pgm.rpgle
OLDTAGRPG3.PGM: OLDTAGRPG3-old_rpg400_modernised.pgm.rpgle