# ISOTODATE.SRVPGM ISOTODATE4.SRVPGM
ART801.PGM: ART801.SQLPRC
ARTLSTDAT.FILE: ARTLSTDAT.VIEW ARTICLE.FILE ORDER.FILE DETORD.FILE
#ISOTODATE.SRVPGM: ISOTODATE.SQLUDF
ORD701.PGM: ORD701.SQLTRG
ARTIINF.FILE: ARTIINF.TABLE
CUSSEQ.DTAARA: CUSSEQ.SQLSEQ
#ISOTODATE4.SRVPGM: ISOTODATE4.SQLUDF
ORDERCUS.FILE: ORDERCUS.VIEW DETORD.FILE ORDER.FILE CUSTOMER.FILE
CUSSEQ.FILE: CUSSEQ.SQLSEQ
ISOTODATE.SRVPGM: ISOTODATE.SQLUDF DAT001.PGM
ISOTODATE4.SRVPGM: ISOTODATE4.SQLUDF DAT002.PGM
ORD701_INSERT_ORDER.PGM: ORD701.SQLTRG